name: Build SunamoExtensions

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoExtensions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoExtensions/SunamoExtensions.csproj

    - name: Build
      run: dotnet build SunamoExtensions/SunamoExtensions.csproj --configuration Release --no-restore

  test:
    name: Test SunamoExtensions.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoExtensions.Tests/SunamoExtensions.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoExtensions.Tests/SunamoExtensions.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoExtensions.Tests/SunamoExtensions.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
